In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
import random
from random import randint
from PIL import Image

In [5]:
def psi_s(sigma, d_s, i_s, j_s, L_img, R_img):
#     print(i_s, j_s, i_s+d_s)
    return np.exp( (-0.5/sigma**2)*(L_img[i_s,j_s]-R_img[i_s + d_s,j_s])**2 )

def psi_s_t(gamma, d_s, d_t, del0):
    return np.exp((-0.5/gamma**2)*np.min( np.array( [(d_s-d_t)**2, del0**2] )))

def M_ts(gamma, d_s, del0, sigma, i_s, j_s, L_img, R_img):
    message = 0
    for i in range(10):
        message += psi_s_t(gamma, d_s, i, del0)*psi_s(sigma, i, i_s, j_s, L_img, R_img)
    return message

def marginal(sigma, i_s, j_s, L_img, R_img, gamma, del0):
    Mu_s = np.zeros(10)
    for i in range(10):
        Mu_s[i] = psi_s(sigma, i, i_s, j_s, L_img, R_img)*(M_ts(gamma, i, del0, sigma, i_s, j_s, L_img, R_img))**4
#     print('\n','sum =', sum(Mu_s), 'Mu_s =', Mu_s )
#     print('\n','sum =', sum(Mu_s),  'Mu_s', Mu_s, 'psi_s =',psi_s(sigma, i, i_s, j_s, L_img, R_img), 'M_ts =', (M_ts(gamma, i, del0, sigma, i_s, j_s, L_img, R_img))**4)
    Mu_s = Mu_s/sum(Mu_s)
    return Mu_s

In [6]:
# L_img = Image.open('desp_bw_left.png')
# R_img = Image.open('desp_bw_right.png')

L_img = Image.open('gray_left.jpg')
R_img = Image.open('gray_right.jpg')

L_img = np.array(L_img)
R_img = np.array(R_img)

# L_img = np.array(L_img[:, 0:256-10])
# R_img = np.array(R_img[:, 0:256-10])
# 288, 384
disparity = np.zeros([255-2-10-3+1, 255-2-3+1])
# i_s = 1
# j_s = 1
for i_s in range(disparity.shape[0]):
    for j_s in range(disparity.shape[1]):
        disparity[i_s,j_s] = np.max(marginal(1, i_s+1, j_s+1, L_img, R_img, 1, 6))
        disparity[i_s,j_s] = disparity[i_s,j_s]*255
    print(i_s)
        
        


C:\Users\Sayan\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sayan\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\Sayan\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in ubyte_scalars
  This is separate from the ipykernel package so we can avoid doing imports until


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240


In [15]:
# disparity = disparity[:, 1:disparity.shape[1]-2]
image = Image.fromarray(disparity.astype('uint8'))
image.show()

In [8]:
print(disparity[0])

[         nan 128.98142971 123.69063359 185.43576785 251.11368532
          nan 154.11093591          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan 255.                  nan
          nan          nan 255.         254.99999612 254.9990496
 127.5        254.98592783 254.99987139          nan          nan
 254.99904712 254.85271748 255.                  nan 127.58073892
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan  31.82520479  74.03560506 103.50873124  69.77387808
  42.7773405   34.16115551  57.23101772 152.06305262 224.87822844
 162.07043951 146.36577556 254.58626295 255.         255.
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan 255. 

In [9]:
A = np.array([[1,2,3], [4,5,6], [8,7,5]])
print(A)
print(A[(1,2),2])

[[1 2 3]
 [4 5 6]
 [8 7 5]]
[6 5]


In [10]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
print(255*255*np.exp(-0.5*255*255))

0.0


In [12]:
np.max(R_img)

255

In [13]:
L_img = Image.open('desp_bw_left.png')
# R_img = Image.open('gray_right.jpg')

L_img = np.array(L_img)
# R_img = np.array(R_img)
print(L_img.shape)

(288, 384)


In [14]:
print(np.exp(0))

1.0
