In [1]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

In [2]:
def psi_s(sigma, d_s, i_s, j_s, L_img, R_img):
    return np.exp( (-0.5/sigma**2)*(L_img[i_s, j_s]-R_img[i_s, j_s+d_s])**2 )

def psi_s_t(gamma, d_s, d_t, del0):
#     print([(d_s-d_t)**2, np.ones(10)*del0**2], '\n')
#     print(np.vstack( ((d_s-d_t)**2, np.ones(10)*del0**2) ), '\n')
    return np.exp((-0.5/gamma**2)*min((d_s-d_t)**2, del0**2))

#     return np.exp((-0.5/gamma**2)*np.min( np.vstack( ((d_s-d_t)**2, np.ones(10)*del0**2) ), 0))
    
def M_ts(gamma, d_s, del0, sigma, i_s, j_s, L_img, R_img):
    message = 0
    for d_t in range(10):
        message += psi_s_t(gamma, d_s, d_t, del0)*psi_s(sigma, d_t, i_s, j_s, L_img, R_img)
    return message

def marginal(sigma, i_s, j_s, L_img, R_img, gamma, del0):
    Mu_s = np.zeros(10)
    for i in range(10):
        Mu_s[i] = psi_s(sigma, i, i_s, j_s, L_img, R_img)*M_ts(gamma, i, del0, sigma, i_s-1, j_s, L_img, R_img)*\
        M_ts(gamma, i, del0, sigma, i_s+1, j_s, L_img, R_img)*M_ts(gamma, i, del0, sigma, i_s, j_s-1, L_img, R_img)*\
        M_ts(gamma, i, del0, sigma, i_s, j_s+1, L_img, R_img)
#     print(Mu_s)
    return Mu_s

# def marginal(sigma, i_s, j_s, L_img, R_img, gamma, del0):
# #     values = np.array([0,1,2,3,4,5,6,7,8,9])
#     Mu_s = psi_s(sigma, values, i_s, j_s, L_img, R_img)*M_ts(gamma, values, del0, sigma, i_s-1, j_s, L_img, R_img)*\
#     M_ts(gamma, values, del0, sigma, i_s+1, j_s, L_img, R_img)*M_ts(gamma, values, del0, sigma, i_s, j_s-1, L_img, R_img)*\
#     M_ts(gamma, values, del0, sigma, i_s, j_s+1, L_img, R_img)
#     return Mu_s

def normal(X):
    X_norm = (X-np.min(X))/(np.max(X)-np.min(X))
    return X_norm

In [3]:
L_img = Image.open('HW0-left-gray.png').convert('L') 
R_img = Image.open('HW0-right-gray.png').convert('L')  
L_img = (np.array(L_img, dtype='f'))
# L_img = normal(L_img)
R_img = np.array(R_img, dtype='f')
# R_img = normal(R_img)
# print(R_img.shape)

# img_L = Image.open('HW0-left-gray.png').convert('L')                          # LEFT-IMAGE (Reference)
# WIDTH, HEIGHT = img_L.size
# I_L = list(img_L.getdata())
# L_img = [I_L[offset:offset+WIDTH] for offset in range(0, WIDTH*HEIGHT, WIDTH)]

# img_R = Image.open('HW0-right-gray.png').convert('L')                         # RIGHT_IMAGE
# WIDTH, HEIGHT = img_L.size
# I_R = list(img_R.getdata())
# R_img = [I_R[offset:offset+WIDTH] for offset in range(0, WIDTH*HEIGHT, WIDTH)]

# print(R_img)

A = np.arange(50,240, 20)
A = A[::-1]
disparity = np.zeros([255-3+1 ,255-10-3+1])
for i_s in range(disparity.shape[0]):
    for j_s in range(disparity.shape[1]):
        disparity[i_s,j_s] = A[np.argmax(marginal(1, i_s+1, j_s+1, L_img, R_img, 1, 3))]
#         disparity[i_s,j_s] = disparity[i_s,j_s]
    print(i_s)
        
        


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252


In [15]:
# disparity_norm = normal(disparity)
# disparity_norm = disparity_norm*255
im = Image.fromarray(disparity)
im.show()
print(disparity[0])

[230.  90. 110. 130. 170. 190. 210. 230. 230. 130. 150. 170. 190. 210.
 230. 230. 230. 210. 230. 230. 230. 230. 230. 230. 230. 230.  50.  70.
  90. 110. 170. 210. 230. 210. 230. 230. 230. 230. 230. 230. 230. 230.
 230. 230. 230.  70. 170. 190. 190. 210. 210. 210. 230. 230. 170. 190.
 210. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230.
 230. 230. 230. 230. 230. 230.  90. 130. 150. 170. 190. 210. 230. 230.
 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230.
 230. 230. 230. 230. 230.  90. 170. 130. 130. 130. 130. 130. 190. 190.
 190. 190. 190. 190. 190. 190. 190. 190. 190. 190. 190. 190. 210. 210.
 230. 230. 230. 110. 130. 150. 170. 190. 210. 230. 230. 230. 230. 230.
 230. 130. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230. 230.
 190. 210.  90. 230. 150. 150. 190. 210. 230. 230. 230. 230. 230.  90.
 230. 230. 230. 230. 230. 230. 230.  50.  50.  70. 170. 150. 190. 190.
 230. 230. 230. 230. 230. 230. 230. 230. 230.  50.  70. 170. 230. 130.
 190. 

In [5]:
# image = Image.fromarray(R_img.astype('uint8'))
# image.show()

In [6]:
A = np.array([1,2,3])
B = np.array([4,5,6])
A = np.vstack((A,B))
print(A)
print(np.min(A,0))

[[1 2 3]
 [4 5 6]]
[1 2 3]


In [7]:
print(disparity)

[[230.  90. 110. ... 150. 170.  90.]
 [230.  70.  90. ... 110.  90. 170.]
 [230.  70. 130. ... 170.  90. 230.]
 ...
 [170. 170. 150. ... 190. 230.  50.]
 [150. 170. 170. ... 170. 150. 230.]
 [170. 170.  90. ... 150. 130. 150.]]


In [8]:
print([A, B])

[array([[1, 2, 3],
       [4, 5, 6]]), array([4, 5, 6])]


In [9]:
A = np.array([[1,2,3],[4,7,8],[5,3,1]])
print(A)
print(np.min(A,1))

[[1 2 3]
 [4 7 8]
 [5 3 1]]
[1 4 1]


In [10]:
print(R_img[0, 1+np.array([1,2,3])])

[70. 74. 75.]


In [11]:
print(1+np.array([1,2,3]))

[2 3 4]


In [12]:
print(R_img[0])

[ 70.  70.  70.  74.  75.  75.  77.  77.  77.  78.  85.  90.  88.  85.
  82.  79.  81.  84.  87.  87. 106. 170. 238. 156.  51.  53.  51.  44.
  40.  43.  43.  43.  49.  50.  51.  38.  79. 204. 253. 255. 255. 255.
 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 254. 236.
 229. 249. 253. 252. 210. 162. 164. 153. 161. 160. 160. 145.  81.  45.
  45.  48.  35.  26.  25.  25.  24.  23.  24.  25.  21.  25.  22.  21.
  70. 125. 157. 150. 183. 242. 249. 241. 244. 254. 254. 253. 254. 255.
 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255.
 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255.
 255. 255. 254. 254. 246. 194.  82.  61. 145. 233. 252. 215. 105.  41.
 101. 145.  96.  76.  70.  91.  87.  70.  93. 106.  83.  79.  69.  62.
  57.  43.  48.  69.  66.  61.  71.  69.  63.  77. 102. 145. 247. 209.
 142. 200. 247. 254. 254. 252. 253. 237. 184. 168. 122. 125. 197. 161.
 119. 222. 220. 126. 102.  92. 111. 114. 101.  84.  95.  97.  96.  90.
 101. 

In [13]:
img_L = Image.open('HW0-left-gray.png').convert('L')                          # LEFT-IMAGE (Reference)
WIDTH, HEIGHT = img_L.size
I_L = list(img_L.getdata())
I_L = [I_L[offset:offset+WIDTH] for offset in range(0, WIDTH*HEIGHT, WIDTH)]

img_R = Image.open('HW0-right-gray.png').convert('L')                         # RIGHT_IMAGE
WIDTH, HEIGHT = img_L.size
I_R = list(img_R.getdata())
I_R = [I_R[offset:offset+WIDTH] for offset in range(0, WIDTH*HEIGHT, WIDTH)]

print(I_R)

[[70, 70, 70, 74, 75, 75, 77, 77, 77, 78, 85, 90, 88, 85, 82, 79, 81, 84, 87, 87, 106, 170, 238, 156, 51, 53, 51, 44, 40, 43, 43, 43, 49, 50, 51, 38, 79, 204, 253, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 236, 229, 249, 253, 252, 210, 162, 164, 153, 161, 160, 160, 145, 81, 45, 45, 48, 35, 26, 25, 25, 24, 23, 24, 25, 21, 25, 22, 21, 70, 125, 157, 150, 183, 242, 249, 241, 244, 254, 254, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 254, 246, 194, 82, 61, 145, 233, 252, 215, 105, 41, 101, 145, 96, 76, 70, 91, 87, 70, 93, 106, 83, 79, 69, 62, 57, 43, 48, 69, 66, 61, 71, 69, 63, 77, 102, 145, 247, 209, 142, 200, 247, 254, 254, 252, 253, 237, 184, 168, 122, 125, 197, 161, 119, 222, 220, 126, 102, 92, 111, 114, 101, 84, 95, 97, 96, 90, 101, 106, 183, 242, 148, 108, 175, 137, 79, 79, 101, 127, 196, 248, 254, 249, 246, 201, 219, 252, 

In [14]:
print(np.asarray(I_R))

[[ 70  70  70 ... 253 253 251]
 [ 72  72  72 ... 253 253 251]
 [ 76  76  76 ... 253 253 251]
 ...
 [ 88  28  25 ...   8  21  58]
 [107  75  25 ...   4  24  61]
 [119 115  47 ...  29  59  76]]
