In [1]:
import numpy as np
import random
from numpy import linalg as LA
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib qt

### The backpropagation algorithm is implemented as follows:

In [27]:
def forward_pass(X, W_ih, W_hj, num_in_node, num_hid_node, num_op_node):
      
    # hidden layer
    Zh = np.sum(W_ih.T*X, axis = 1) # Activation potential
    S_Zh = sigmod_fun(Zh)                                        # Activation

    # Output layer
    Yj = np.sum( W_hj.T*S_Zh, axis = 0 ) # Activation potential
    S_Yj = sigmod_fun(Yj)                                              # Activation
    
    return Zh, Yj, S_Zh, S_Yj

def back_propagation(X, d, W_ih, W_hj, Zh, Yj, S_Zh, S_Yj, eta, num_in_node, num_hid_node, num_op_node):
    error = 0.5*np.sum((S_Yj - d)*(S_Yj - d))
    e = (S_Yj - d)
    Sd_Yj = sigmod_deriv_fun(Yj)
    Sd_Zh = sigmod_deriv_fun(Zh)
    a = np.ones((num_hid_node, num_op_node))*np.reshape(e,(num_op_node,1))
    b = np.ones((num_hid_node, num_op_node))*np.reshape(Sd_Yj, (num_op_node,1) )
    c = np.ones((num_hid_node, num_op_node))*np.reshape(S_Zh, (num_hid_node,1))
    
    # weight update hidden to output
    W_hj = np.reshape(W_hj, (num_hid_node,num_op_node)) - eta*(a*b*c)
    
    # weight update input to hidden
    gam = np.sum(e*Sd_Yj*np.reshape(W_hj, (num_hid_node,1,num_op_node)), axis=2)
    a = np.ones((num_hid_node, num_op_node))*np.reshape(gam, (1,num_hid_node))
    b = np.ones((num_hid_node, num_op_node))*Sd_Zh
    c = np.ones((num_hid_node, num_op_node))*X
    W_ih = W_ih - eta*(a*b*c)
    
    return error, W_hj, W_ih

def sigmod_fun(X):
    return 1/(1+np.exp(X))

def sigmod_deriv_fun(X):
    X_sig = sigmod_fun(X)
    Z = X_sig*(1-X_sig)
    return Z


In [52]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
d = np.array([[0],[1],[1],[0]])
num_in_node = 2
num_hid_node = 2
num_op_node = 1
num_ips = 4
epochs = 10000
W_ih = np.random.random((num_in_node, num_hid_node))
W_hj = np.random.random((num_hid_node, num_op_node))
W_hj = np.reshape(W_hj, (num_hid_node,))
eta = 0.09

for i in range(epochs):
    for j in range(num_ips):
        Zh, Yj, S_Zh, S_Yj =  forward_pass(X[j,:], W_ih, W_hj, num_in_node, num_hid_node, num_op_node)
        error, W_hj, W_ih = back_propagation(X[j,:], d[j], W_ih, W_hj, Zh, Yj, S_Zh, S_Yj, eta, num_in_node, num_hid_node, num_op_node)
        W_hj = np.reshape(W_hj, (num_hid_node,))
        

    

In [58]:
print(error)
print(X[3,:])
Zh, Yj, S_Zh, S_Yj =  forward_pass(X[0,], W_ih, W_hj, num_in_node, num_hid_node, num_op_node)
print(S_Yj)

0.12499498190322991
[1 1]
0.00504273369666132


In [59]:
0.4942880298380033
A = np.array([1,2])
B = np.array([7,3])
C = np.array([[1,2], [1,4], [2,3]])
D = np.reshape(C,(3,1,2))
print(C)
print(D)

[[1 2]
 [1 4]
 [2 3]]
[[[1 2]]

 [[1 4]]

 [[2 3]]]


In [60]:
print(A*B)
E = A*B*D
print(E)

[7 6]
[[[ 7 12]]

 [[ 7 24]]

 [[14 18]]]


In [63]:
print(np.sum(E, axis = 2))

[[19]
 [31]
 [32]]


In [ ]:
print(np.reshape(C, (2,)))

In [64]:
AA = np.ones((2,2))
BB = np.array([1,2])
print(AA*BB)

[[1. 2.]
 [1. 2.]]


In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([4,5])
print(A*B)


[[ 4 10]
 [12 20]]


In [121]:
A = np.array([[1],[2],[3]])
print(1/(1+np.exp(A)))

[[0.26894142]
 [0.11920292]
 [0.04742587]]


In [131]:
B = np.array([[4],[5],[6]])
print(A.T)

[[1 2 3]]


In [69]:
print(np.reshape(1,(1,1)))

[[1]]


In [72]:
A = np.array(1)
print(np.reshape(A,(1,1)))

[[1]]
